### ISSUE TITLE
[Metadata] Better desktop entry names

### ISSUE THREAD

**Issue by futurelinuxapp** [flathub/com.github.iortcw.iortcw#8]
Hi, I'd like to bring a up few issues with the current metadata for desktop entries.

1) They do not specify the name of the sourceport, 'iortcw'.

<s>2) They conflict with the Wine installer names. See attached screenshot.</s>

<s>3) Flathub [Quality guidelines](https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines#just-the-name) explicitly call out (Parenthesized) items as a bad example.</s>

Suggestion:

Change desktop entry names to 'iortcw', 'iortcw Multiplayer'.

![Screenshot_20240302_080016](https://github.com/flathub/com.github.iortcw.iortcw/assets/160535523/1fa01aec-6103-453c-897c-2977d2db07ce)

PR: https://github.com/flathub/com.github.iortcw.iortcw/pull/9

**Comment by Eonfge** [comment]
Could you discuss this with Upstream? Not sure what they would prefer.

See here: https://github.com/iortcw/iortcw/issues/103

I'm a little reluctant to make such big changes while the package has been online like this, longer then quality guidelines even.

**Comment by futurelinuxapp** [comment]
> Could you discuss this with Upstream? Not sure what they would prefer.
> 
> See here: [iortcw/iortcw#103](https://github.com/iortcw/iortcw/issues/103)

That issue has been open for over 3 years. I don't think linux meta info passes the smoke test over there.

> I'm a little reluctant to make such big changes while the package has been online like this, longer then quality guidelines even.

I don't see the logic this. Sounds more like a typical human fear of change thing. I think the metadata is simply inaccurate, and can it be improved.

**Comment by Eonfge** [comment]
> I don't see the logic this. Sounds more like a typical human fear of change thing. I think the metadata is simply inaccurate, regardless of the latest Flathub guidlines, and it can be improved.

An ad-hominem does not really advance your cause. Case remains that I've been maintaining this package since September 2019, with ~13,000 users and that I don't think this change is in the interest of all those users. Using a name like `iortcw` would conflict with the [GNOME HIG](https://developer.gnome.org/hig/guidelines/app-naming.html) and [KDE HIG](https://develop.kde.org/hig/style/writing/brandnames/).

A minor change I can agree with, is to prefix the desktop-names with `IO` to avoid trademark violations.

`IO Return to Castle Wolfenstein (singleplayer)`
`IO Return to Castle Wolfenstein (multiplayer)`

There is another suggestion though. In the past, we discussed different icons for both single and multiplayer. This would also match the Microsoft Windows installation of RTCW that most will be known with. Not sure if I can find those mock-ups.

**Comment by futurelinuxapp** [comment]
> An ad-hominem does not really advance your cause.

Our cause.

And I'm sorry, where in post #3 do you feel personally attacked and discredited? Fear of change change *is* human, and *is* typical. That you are now considering adding "IO" to the desktop entry is proof enough that the metadata *is* inaccurate.

I also notice that [you created the flatpak metadata](https://github.com/flathub/com.github.iortcw.iortcw/commit/b0eced83b6a206ace5128aea786212685aa726e6). While I applaud and agree with the upstream ethos, a appreaciate little logic and civility can get the work done. There's also an obvious chicken-egg issue in regards to upstreaming what-in-what-order.

And if you want to ping the iortcw issue tracker again. Do it yourself, or quoteping thing if it keeps your sense of individuality.

> Case remains that I've been maintaining this package since September 2019, with ~13,000 users and that I don't think this change is in the interest of all those users.

Not sure what you are trying to flex here, but that is a loaded statement. Let me unpack it.

The metadata has been inaccurate since September 2019. The number of downloads is totally irrelevant. Most people just want to download "iortcw" and play the sourceport.

I'll add that ioquake3 has been published to Flathub, and the desktop entry is:

```ioquake3```

Not:

```IO Quake III Arena```

The reason I opened this issue in the first place is because "iortcw" is, to my accessment, the common nomenclature. Most, documentation refers to the sourceport as "iortcw".

> Using a name like `iortcw` would conflict with the [GNOME HIG](https://developer.gnome.org/hig/guidelines/app-naming.html) and [KDE HIG](https://develop.kde.org/hig/style/writing/brandnames/).

I also think we are both conflating guidelines with standards. Flathub's guidelines don't necessitate removing parenthetical naming. I see lots and lots of apps that use parenthesis so I'm again willing to back off in that regard.

However, that also applies to GNOME/KDE guidelines. They do not necessitate "IO Return to blah blah" I am still not willing to back down on "iortcw" though. 
I've had time to install the GOG version of RTCW and I'm backing off of of adding (Singleplayer).

GOG.com desktop entry names:
```
Return to Castle Wolfenstein
Return to Castle Wolfenstein (Multiplayer)
```

I think the entries naturally sort themselves better without "Singleplayer" in the actual singleplayer description.

Therefore, I think the least bad desktop entry names would be

```
iortcw
iortcw (Multiplayer)
```


> There is another suggestion though. In the past, we discussed different icons for both single and multiplayer. This would also match the Microsoft Windows installation of RTCW that most will be known with. Not sure if I can find those mock-ups.

What? What is this? Can you stay on topic? I'm also closing my PR due to lack of feedback.
